# Generated by Django 6.0.7 on 2026-07-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('password', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=200)),
            ],
        ),
    ]
