# Generated by Django 6.0.7 on 2026-07-26 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'managed': True, 'ordering': ['name'], 'verbose_name': 'Student Data', 'verbose_name_plural': 'Student Data'},
        ),
        migrations.AlterModelTable(
            name='students',
            table='students_informations',
        ),
    ]
